# 4- Create a ClusterRoleBinding which should be named as
# haproxy-cluster-role-binding-devops under the same namespace. Define roleRef apiGroup
# should be rbac.authorization.k8s.io, kind should be ClusterRole, name should be
# haproxy-cluster-role-devops and subjects kind should be ServiceAccount, name should be
# haproxy-service-account-devops and namespace should be haproxy-controller-devops.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-cluster-role-binding-devops
  namespace: haproxy-controller-devops
subjects:
- kind: ServiceAccount
  name: haproxy-service-account-devops
  namespace: haproxy-controller-devops
roleRef:
  kind: ClusterRole
  name: haproxy-cluster-role-devops
  apiGroup: rbac.authorization.k8s.io