#2- Create a ServiceAccount haproxy-service-account-devops under the same namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-service-account-devops
  namespace: haproxy-controller-devops
  